CREATE USER 'track-time'@'%' IDENTIFIED BY 'TrackTime20*';
GRANT ALL PRIVILEGES ON *.* TO 'track-time'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'laravel'@'%' IDENTIFIED BY 'TrackTime20*';
GRANT ALL PRIVILEGES ON *.* TO 'laravel'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
