CREATE USER 'admin'@'%' IDENTIFIED BY 'TrackTime20*';
GRANT ALL PRIVILEGES ON *.* TO 'gestion-stock'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'laravel'@'%' IDENTIFIED BY 'TrackTime20*';
GRANT ALL PRIVILEGES ON *.* TO 'laravel'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
